import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/app/components/Header/Header";
import { SideMenu } from "@/app/components/SideMenu/SideMenu";
import { Main } from "@/app/components/Main/Main";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <UserProvider>
        <body>
          <div className="">
            <Header />
            <div className="max-w-8xl mx-auto px-4 sm:px-6 md:px-8">
              <SideMenu />
              <Main>{children}</Main>
            </div>
          </div>
        </body>
      </UserProvider>
    </html>
  );
}
