name: Next.js Build

on:
  pull_request:
    branches:
      - main

jobs:
  next_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - uses: actions/cache@v3
        id: cache-npm
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: |
          npm install
      - name: App Build
        env:
          # secrets
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_API_CLIENT_SECRET: ${{ secrets.AUTH0_API_CLIENT_SECRET }}
          AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
          # variables
          AUTH0_BASE_URL: ${{ vars.AUTH0_BASE_URL }}
          AUTH0_CLIENT_ID: ${{ vars.AUTH0_CLIENT_ID }}
          AUTH0_API_CLIENT_ID: ${{ vars.AUTH0_API_CLIENT_ID }}
          AUTH0_ISSUER_BASE_URL: ${{ vars.AUTH0_ISSUER_BASE_URL }}
          AUTH0_AUDIENCE: ${{ vars.AUTH0_AUDIENCE }}
          AUTH0_SCOPE: ${{ vars.AUTH0_SCOPE }}
        run: npm run build
